### ISSUE TITLE
css of gradient

### ISSUE THREAD

**Issue by mmfs37** [caro401/royal-velvet#13]
I know this is kind of unthankful of your work, but I do like the minimal theme more than the royal velvet because of the minimal aesthetic. However I wish I could implement your beautiful gradient into my custom theme. 
By looking into your css I thought that this part would finally make it work:
```
h1,
.cm-header-1 {
  -webkit-text-fill-color: transparent;
  background-clip: text;
  -webkit-background-clip: text;
  background-image: linear-gradient(
    var(--134),
    var(--#ff80bf) 0,
    var(--#ffca80) 100%
  );
} /*Source Mode*/
``` 

However it does not. The Header just goes transparent. When experimenting I could repalce the "transparent" of line 3 with any colour and the heading would change its colour to that. 
So now I know how you did it and what happens. Your way of a gradient is probably to "draw" a box with a gradient with the given variables and then clip it to the text. 

In my css snippet adaptation the drawing of the box does not work. The text is probably ready to get clipped and is transparent, but yeah nothing to clip there.

-> therefore I must be missing a function or whatsoever to "draw" / create that gradient. 
(btw I never did css custom this is my first time so sorry if I misinterpreted a lot. I do know nothing and try to go at it with simple logic thinking, but as you can see it does not really help)

I could find no place where you establish the function. Due to no knowlede of css I think its not a integrated function. Otherwise it would work out of the box with my obsidian right?

**Comment by caro401** [comment]
Ah I think you may be a little confused about how I'm using CSS custom properties in the theme - I think you might be referring to custom properties you haven't defined anywhere (like `var(--134)`), so they aren't being interpreted as colours to override the transparent. [Here's some docs](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) if you want to read more about how this works, and [some more info about linear-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient).

Does the below snippet work for you? Notice the missing `var` and `--` in the `background-image` values

```css
h1,
.cm-header-1 {
  -webkit-text-fill-color: transparent;
  background-clip: text;
  -webkit-background-clip: text;
  background-image: linear-gradient(
    134deg, /* the angle of the gradient in degrees */ 
    #ff80bf 0, /* The colour the gradient starts at */
    #ffca80 100% /* the colour the gradient ends at */ 
  );
}
```
