### ISSUE TITLE
Love the theme, here's some CSS I'm using to make it look cleaner and more to my taste

### ISSUE THREAD

**Issue by firinael** [caro401/royal-velvet#24]
![image](https://user-images.githubusercontent.com/67032657/203901913-b0e1172f-b37a-466a-afb3-1d9d4012dd80.png)

```css
body {
    --heading-font                    : "Lexend Deca Semibold";
    --font-monospace                  : "JetBrains Mono";
    --font-text                       : "iA Writer Quattro S";
    --table-header-color              : var(--black);
    --table-header-font               : var(--heading-font);
    --interactive-accent              : var(--red) !important;
    --interactive-accent-hover        : var(--orange) !important;
    --text-on-accent                  : var(--black) !important;
    --background-modifier-border-hover: transparent;
    --modal-border-color              : transparent;
    --prompt-border-color             : transparent !important;
    --background-modifier-border-focus: transparent !important;
    --background-modifier-boder       : transparent !important;
    --default-font                    : "Lexend Deca";
    --input-shadow                    : none !important;
    --blockquote-border-color         : none;
}

.kanban-plugin__autocomplete-item-active.kanban-plugin__ignore-click-outside em {
    color: var(--text-on-accent) !important;
}

.block-language-simple-time-tracker {
    font-family: var(--font-interface);
}

.markdown-preview-sizer {
    padding-bottom: 0 !important;
    min-height    : fit-content !important;
}

.menu-item-icon {
    color: var(--green);
}

em,
.cm-s-obsidian .cm-em {
    font-family: "iA Writer Quattro S" !important;
    font-style : italic !important;
}

.setting-item-control *:not(input[type="text"],
    input[type="search"],
    input[type="email"],
    input[type="password"],
    input[type="number"]),
.clickable-icon {
    cursor: pointer !important;
}

.checkbox-container:not(.is-enabled) {
    background-color: var(--blackXDark) !important;
}

.suggestion-highlight,
.search-result-file-matched-text {
    color: var(--purple);
}

.explorable {
    padding-right: 4px !important;
    padding-left : 4px !important;
}

img {
    display      : block !important;
    margin-left  : auto !important;
    margin-right : auto !important;
    margin-top   : 20px !important;
    margin-bottom: 20px !important;
    border-radius: var(--radius-s);
}

.math.math-block.cm-embed-block,
.markdown-preview-view .math.math-block mjx-container.MathJax {
    background-color: var(--blackDark);
    border-radius   : var(--radius-s);
    border-left     : 4px solid var(--purple);
    border-right    : 4px solid var(--pink);
}

.markdown-preview-view .math.math-block mjx-container mjx-math.MJX-TEX {
    padding-top   : 14px;
    padding-bottom: 14px;
}

blockquote,
.HyperMD-quote {
    border-top-color   : transparent !important;
    border-bottom-color: transparent !important;
    border-right-color : transparent !important;
    border-radius      : var(--radius-s) !important;
    border-left-color  : var(--red) !important;
}

.cm-indent::before {
    border-width: 2px !important;
    border-color: var(--red) !important;
}

.markdown-rendered.show-indentation-guide li>ul::before,
.markdown-rendered.show-indentation-guide li>ol::before {
    border-width: 2px !important;
    border-color: var(--red) !important;
    left        : -13px;
}

.setting-item-heading .setting-item-name,
.vertical-tab-header-group-title {
    text-transform: uppercase !important;
}

.cm-highlight {
    color: var(--yellow) !important;
}

.cm-formatting-quote {
    color: var(--text-muted) !important;
}

.cm-em.cm-strong,
strong>em {
    color: var(--red);
}

mjx-container.MathJax {
    -webkit-text-fill-color: var(--text-normal);
}

.MJX-TEX {
    font-size: 1.2em !important;
}

em,
.cm-em {
    font-family: var(--font-text) !important;
}

.cm-hmd-internal-link,
.cm-hmd-internal-link .cm-underline,
a.internal-link {
    -webkit-text-fill-color: var(--green) !important;
    background             : transparent !important;
    text-decoration        : none !important;
}

:is(.cm-hmd-internal-link .cm-underline,
    .cm-hmd-internal-link,
    a.internal-link):hover {
    text-decoration-line   : none !important;
    -webkit-text-fill-color: var(--yellow) !important;
}

mjx-mtable>*>mjx-itable mjx-mtr:not(:first-of-type) mjx-mtd {
    padding-top: 1.2em !important;
}

.cm-link,
.cm-link .cm-underline,
a.external-link {
    -webkit-text-fill-color: var(--yellow) !important;
    background             : transparent !important;
    text-decoration        : none !important;
    text-decoration-line   : none !important;
}

:is(.cm-link,
    .cm-link .cm-underline,
    a.external-link):hover {
    -webkit-text-fill-color: var(--green) !important;
    text-decoration        : underline !important;
}

.titlebar-button.mod-close:hover {
    color: var(--black);
}

button {
    font-family: var(--font-interface) !important;
    cursor     : pointer !important;
}

.HyperMD-header,
.markdown-preview-view :is(h1, h2, h3, h4, h5, h6) {
    font-family: var(--heading-font);
}

table {
    margin-left  : auto;
    margin-right : auto;
    border-width : 2px;
    text-align   : center;
    font-family  : var(--font-interface);
    border-radius: var(--radius-s);
}

.cm-blockid,
.titlebar-text {
    opacity: 0;
}

.cm-active .cm-blockid,
.cm-blockid:hover {
    opacity: 1;
}

table tr th {
    font-family: var(--heading-font);
    font-size  : 1.2em;
    padding    : 8px 15px !important;
    border     : none !important;
    text-align : center !important;
    font-size  : var(--font-ui-medium) !important;
}

.markdown-source-view.cm-s-obsidian.mod-cm6 .HyperMD-table-row.HyperMD-table-row-0.cm-line {
    color: var(--text-normal) !important
}

.workspace-ribbon.mod-left,
.sidebar-toggle-button.mod-right,
.status-bar,
.cm-s-obsidian .external-link,
.frontmatter-container,
.workspace-leaf-content[data-type=kanban]>.view-header {
    display: none;
}

.workspace-tab-header:not(:hover) .workspace-tab-header-inner-close-button,
.workspace-tab-header-container:not(:hover) .clickable-icon {
    visibility: hidden;
}

.cm-s-obsidian .external-link,
a.external-link {
    background-image: none !important;
    padding-right   : 0px !important;
}

/* pseudometa */
/* Image Alt as caption
(except when no explicit alt is provided and urls are the alt text) */
body:not(.no-image-alttext-caption) .image-embed[alt]:not([alt$=".png"], [alt$=".jpg"], [alt$=".jpeg"], [alt$=".tiff"])::after {
    display: block;
    content: attr(alt);

    font-family: var(--font-text);
    font-size  : var(--font-smaller);
    font-style : italic;

    color: var(--text-muted);

    word-spacing: -3px;

    margin-top   : -1em;
    margin-bottom: 1em;
}

.markdown-preview-view img[src] {
    border       : var(--thin-muted-border);
    border-radius: var(--radius-s);
}

/* centers image and image caption */
.image-embed[alt]::after {
    text-align: center;
}

.view-content img {
    display     : block;
    margin-right: auto;
    margin-left : auto;
}

/* ───────────────────────────────────────────────── */
/* << Overlaying Sidebar
──────────────────────────────────────────────────── */

.mod-right-split {
    position: absolute;
    right   : 0;
}
```
