### ISSUE TITLE
Feature Request: Light theme

### ISSUE THREAD

**Issue by firinael** [caro401/royal-velvet#25]
**Feature Requested**
A version of the theme using light (white?) background colours.

**Relevant Screenshots**
I'm thinking based on the old Mac aesthetic:
![screenshot](https://img.wallpaper.sc/desktop/images/5k/thumbnail/desktop-pc-1920x1080-thumbnail_00089.jpg)
A light version of this theme while keeping it as colourful and having the gradients, but with a pure white background and everything else, would be awesome.

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)

**Comment by WillsterJohnson** [comment]
Thrown together a mock-up of what this might look like. @firinael is this what you envisioned?

![old apple logo based light theme](https://user-images.githubusercontent.com/85991558/214935180-eaf34483-cb43-4d19-b401-b5291965ccb1.png)

The green and yellow need tweaking to prevent the h3 from looking so muddy, but other than that I'm liking the Apple logo colors

**Comment by LEFD** [comment]
Your mock-up looks really good! Would you be able to push your dev branch, so I could check it out for myself?

**Comment by WillsterJohnson** [comment]
sure, heres the branch https://github.com/WillsterJohnson/royal-velvet/tree/light-theme

**Comment by LEFD** [comment]
Just checked it out. I'm impressed by how good it looks, considering you only changed the color vars. I really like that code blocks etc. are lighter than the background. Would you be willing to iron out the small issues?

**Comment by WillsterJohnson** [comment]
> I'm impressed by how good it looks, considering you only changed the color vars

It's a well designed bit of CSS, totally customisable off the back of just a few vars.

> Would you be willing to iron out the small issues?

sure, I think the only problems are the transparent colors and the muddy h3 gradient.

It would make sense to change the names of some of the variables given that they're no longer dark theme specific (eg, `--black` is white in light theme), so I'll change those to be more light/dark agnostic also. The color names are close enough to keep.

I'd like to know your thoughts on reducing the `.theme-dark` and `.theme-light` sections down to just some hue variables and doing the rest in css math. The dark theme would remain visually identical, and the light theme would fall into strict boundaries.
My reasoning being is that the entire UI being controlled by a handful of variables would mean that customising this theme via a snippet would be incredibly easy and take up about 10 lines of css.

That reduction aside, I'll get the colors corrected and start hunting bugs tonight.

**Comment by LEFD** [comment]
> It would make sense to change the names of some of the variables given that they're no longer dark theme specific (eg, --black is white in light theme), so I'll change those to be more light/dark agnostic also. The color names are close enough to keep.

go ahead

> I'd like to know your thoughts on reducing the .theme-dark and .theme-light sections down to just some hue variables and doing the rest in css math.

Could you provide a quick example?

**Comment by WillsterJohnson** [comment]
instead of;
```css
.theme-dark {
  --pink: hsl(330, 100%, 75%);
  --pink-100: hsla(330, 100%, 75%, 0.1);
  // all other colors
}
.theme-light {
  --pink: hsl(...);
  --pink-100: hsla(...);
  // all other colors
}
// snippet must overwrite all colors and color variants directly
```
do;
```css
.theme-dark {
  --global-sat: 100%;
  --global-lit: 75%;
  --pink-hue: 330;
  // other hues only
}
.theme-light {
  // same here
}
body {
  --pink: hsl(var(--pink-hue), var(--global-sat), var(--global-lit);
  // etc
}
// snippet need only modify ~10 values (sat, lit, hues of pink/orange/yellow/green/cyan/purple/red/pink-purple)
```

The low level control also will make any future style settings customisations easier if they alter color in any way.
I'm not tied to it, this is just my preference when working on websites; if things are related, enforce it with a `--var`
