### ISSUE TITLE
[BUG] Table title is almost invisible 

### ISSUE THREAD

**Issue by rahaaatul** [caro401/royal-velvet#43]
**Describe the Bug**
A table title is almost invisible, fading with background color.

**Relevant Screenshots**

![Screenshot_2024_0912_115423](https://github.com/user-attachments/assets/0024b763-4e09-4f3e-bc17-49edf5b3cd34)

![Screenshot_2024_0912_115050](https://github.com/user-attachments/assets/7c6304f4-7389-4bbf-9817-a1c82302e962)

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. Create a table 

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [ ] Source Mode
- [x] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [ ] Public Release (Desktop)
- [x] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by LEFD** [comment]
Thanks a lot for the bug report! it looks like you are using **bold** text in the tables header, which clashes with its background gradient. I have never thought of that occurrence 😄

**Comment by LEFD** [comment]
a possible fix could be using the light theme colors for colored text on gradients for the dark theme and vice versa. this improves readability but looks bad imo.
![2024-09-12 23_59_55-Window](https://github.com/user-attachments/assets/56888044-a95b-40f5-a91c-aa41b8039b02)
![2024-09-13 00_00_23-Window](https://github.com/user-attachments/assets/0faae2df-2654-4ca7-87a8-34a9612d41a8)

another option would be removing the color of emphasised text on gradients altogether:
![2024-09-13 00_01_17-Window](https://github.com/user-attachments/assets/fd6d7257-adb5-4b90-833d-18262674e00e)

adding a stroke to the text does not look good either.

if anyone got any suggestions, feel free to share them!

**Comment by rahaaatul** [comment]
What's the CSS for this particular part? I'd like to try some color variants and give you feedback.

**Comment by LEFD** [comment]
@rahaaatul check out e53fdf6edf2468c4ff0fbf1ea0828ab2ca243f0f.

other types of text, like links might need some styling as well. but we could do this later. for now, we need to find something that works for this theme.

**Comment by rahaaatul** [comment]
@LEFD what do you think of going custom?

![image](https://github.com/user-attachments/assets/94ece0b1-0adf-4ec8-aa90-452a0559a10d)

```css
/* bold in table header */
th strong,
.table-cell-wrapper .cm-s-obsidian .cm-strong {
    -webkit-text-fill-color: transparent;
    background-clip: text;
    -webkit-background-clip: text;
    background-image: linear-gradient(
      var(--gradientDegree),
      var(--blue) 0%,
      var(--yellow) 100%
    );
}
```

**Comment by LEFD** [comment]
@rahaaatul using a custom gradient for colored, bold text on another gradient might work for one type of emphasized text. But this color gradient doesn't work with light mode and we would need to account for other types of colored text, like links.

I was thinking of putting a box around colored text on gradients:
![image](https://github.com/user-attachments/assets/3a3e6ca7-faae-4eee-9bf7-52c314eeac77)

```css
th strong,
.table-cell-wrapper .cm-s-obsidian .cm-strong,
th em,
.table-cell-wrapper .cm-s-obsidian .cm-em,
th strong > em,
.table-cell-wrapper .cm-em.cm-strong,
th a.internal-link,
th a.external-link {
  background-color: var(--background-primary);
  border: var(--tag-border-width) solid var(--tag-border-color);
  font-size: var(--tag-size);
  font-weight: var(--tag-weight);
  text-decoration: var(--tag-decoration);
  border-radius: 4px;
  padding: 0.125em 0.25em ;
}
```

What do you think?
