### ISSUE TITLE
Code is in grey - not ideal.  Green, perhaps?

### ISSUE THREAD

**Issue by clearoak** [caro401/royal-velvet#49]
I'm writing ordinary text, which is bright white, and quoting code snippets. (Using the ``` syntax).   Unfortunately, these are much darker, a grey, and I need to turn up the brightness on the screen to even read this, and then the white is too bright.   It would be much better if the code stood out, being printed in green, perhaps, like on an old VT100 type terminal.  Obviously, it's the code that's the important bit. Aside from this, I'm a big fan of the colourful scheme.   No idea why this is the only one like it.    For later, perhaps a solarised background?

**Comment by LEFD** [comment]
Thanks for bringing attention to this issue. 
Have you disabled all CSS snippets, that might interfere with code blocks?

To be frank, the contrast of code blacks (and muted text in general) isn't the best (duh). Code blocks in its current state are failing the WCAG AAA test. A slight increase in contrast of muted text, would benefit the theme as a whole greatly. I'm considering reducing the brightness of normal white text as well.

I like the idea of making code blocks stand out more. This could be realized using a CSS snippet, as I think your suggestion does not fit the theme.

```css
.theme-dark {
  --solarized-background: #002b36;
  --vt100-foreground: #5afab8; /* I made this color up, it looks good to me */
}

/* code block and indented code in editing mode */
.markdown-source-view.mod-cm6 .cm-line.HyperMD-codeblock,
.markdown-rendered pre code,
.cm-s-obsidian span.cm-inline-code.cm-hmd-indented-code {
  color: var(--vt100-foreground);
  background-color: var(--solarized-background);
}

/* code blocks border in reading mode */
.markdown-rendered pre {
  background-color: var(--solarized-background);
}
```
